import { mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';

const outputDir = new URL('../test-screenshots/', import.meta.url);
await mkdir(outputDir, { recursive: true });

const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
await page.goto('http://127.0.0.1:5174', { waitUntil: 'networkidle' });
await page.getByRole('button', { name: '角色图鉴' }).click();
await page.getByRole('button', { name: /里安娜路西艾拉/ }).waitFor();
await page.screenshot({ path: fileURLToPath(new URL('hero-library.png', outputDir)), fullPage: true });
await page.getByRole('button', { name: /高级筛选/ }).click();
await page.screenshot({ path: fileURLToPath(new URL('hero-advanced-filter.png', outputDir)) });
await page.locator('.advanced-filter-content').evaluate((element) => { element.scrollTop = element.scrollHeight; });
await page.screenshot({ path: fileURLToPath(new URL('hero-effect-filter.png', outputDir)) });
await page.getByRole('button', { name: '关闭高级筛选' }).click();
await page.getByRole('button', { name: /里安娜路西艾拉/ }).click();
await page.getByRole('button', { name: '查看角色装备' }).waitFor();
await page.screenshot({ path: fileURLToPath(new URL('hero-detail.png', outputDir)), fullPage: true });
await page.locator('.library-hero-title-button').click();
await page.screenshot({ path: fileURLToPath(new URL('hero-alias-editor.png', outputDir)) });
await page.getByRole('button', { name: '关闭别名设置' }).click();
await page.getByRole('button', { name: '编辑角色数据' }).click();
await page.screenshot({ path: fileURLToPath(new URL('hero-data-editor.png', outputDir)) });
await page.getByRole('button', { name: '关闭角色数据编辑器' }).click();
await page.locator('.effect-tags button').first().click();
await page.screenshot({ path: fileURLToPath(new URL('hero-effect-dialog.png', outputDir)) });
await page.keyboard.press('Escape');
await page.getByRole('button', { name: '查看角色装备' }).click();
await page.getByText('角色最终面板').waitFor();
await page.screenshot({ path: fileURLToPath(new URL('hero-build.png', outputDir)), fullPage: true });
await page.getByRole('button', { name: '神器图鉴' }).click();
await page.getByPlaceholder('搜索神器名称或英文名').waitFor();
await page.screenshot({ path: fileURLToPath(new URL('artifact-library.png', outputDir)), fullPage: true });
await page.getByPlaceholder('搜索神器名称或英文名').fill('扭曲欲望');
await page.locator('.artifact-card').first().click();
await page.screenshot({ path: fileURLToPath(new URL('artifact-detail.png', outputDir)), fullPage: true });
await page.evaluate(() => localStorage.removeItem('epic7.tools.heroDetail.v1'));
await page.getByRole('button', { name: '角色图鉴' }).click();
await page.getByPlaceholder('搜索角色名称、英文名或昵称').fill('雅碧凯');
await page.locator('.hero-card').first().click();
await page.getByRole('heading', { name: '专属装备' }).waitFor();
await page.screenshot({ path: fileURLToPath(new URL('hero-exclusive-equipment.png', outputDir)), fullPage: true });
await page.getByRole('button', { name: '战斗计算' }).click();
await page.getByText('装备预设').first().waitFor();
await page.screenshot({ path: fileURLToPath(new URL('calculator-build-presets.png', outputDir)), fullPage: true });
await browser.close();
